version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install -r docs/requirements.txt
    post_build:
      - python docs/complete_translate.py

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt