version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_build:
      - python3 docs/complete_translate.py
      - cd docs && make -e SPHINXOPTS="-D language='zh_CN'" html
      - mkdir -p $READTHEDOCS_OUTPUT/html/zh_CN || true
      - cp -r docs/_build/html/* $READTHEDOCS_OUTPUT/html/zh_CN/ || true

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt