version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - cd docs && python3 rtd_translate.py

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt