version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git submodule update --init --recursive
    pre_build:
      - pip install -r docs/requirements.txt
    post_build:
      - python docs/complete_translate.py

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip
  - epub

python:
  install:
    - requirements: docs/requirements.txt

submodules:
  include: all

search:
  ranking:
    api.html: 1
    quickstart.html: 2
    installation.html: 3

# Multi-language configuration
languages:
  - en
  - zh_CN