version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # Apply translations first
    - python3 docs/complete_translate.py
    # Build English version
    - cd docs && sphinx-build -b html . _build/html
    # Build Chinese version to separate directory  
    - cd docs && sphinx-build -b html -D language='zh_CN' . _build/html/zh_CN

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt